server:
  port: 8080
spring:
  application:
    name: screeenly
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
screeenly:
  storage:
    type: local
    path: uploads/screenshots
  screenshot:
    timeout: 30 # seconds
    user-agent: screeenly-bot 2.0
    disable-sandbox: false
